[build]
  base = "frontend/"
  publish = "frontend/out"
  command = "next build"
  functions = "frontend/netlify"

[build.environment]
  NEXT_SERVERLESS = "true"
  SANITY_PROJECT_ID="9up46puq"
  SANITY_DATASET="production"
  BUILD_LANGUAGES = "en-US,it-IT"
  BUILD_CMS = "sanity"

[[plugins]]
  package = "@netlify/plugin-nextjs"
