name: Sangbok CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Node.js dependencies and Cypress
        id: node-cache
        uses: actions/cache@v2
        with:
          path: |
            frontend/node_modules
            ~/.cache/Cypress
          key: my-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Run lint
        run: yarn lint

      - name: Run format check
        run: yarn format-check

      - name: Build Next app
        run: yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
          command: yarn end:test
          working-directory: ./frontend
